### ISSUE TITLE
Veille sur l'API Moodle et le format Moodle XML

### ISSUE THREAD

**Issue by November304** [enzofrnt/AUTO-QCM#21]

**Comment by November304** [comment]
Source des informations pour le format moodle XML des quiz pour l'import : 
https://docs.moodle.org/4x/fr/Format_XML_Moodle

**Comment by Kilianspore** [comment]
La classe Quiz de l'API moodle : 
https://wimski.org/api/3.8/dc/d8f/classquiz.html

**Comment by November304** [comment]
Attente de création d'un cours pour pouvoir tester ce qu'on a trouvé
